import { SettingsType } from '../types/state'

export const preSettings: SettingsType[] = [
  {
    tavern: 'On The House',
    location: 'Harmondale',
    start: {
      tower: 15,
      wall: 5,
      brickProd: 2,
      gemProd: 2,
      recruitProd: 2,
      bricks: 10,
      gems: 10,
      recruits: 10,
    },
    win: {
      tower: 30,
      resource: 100,
    },
    cardsInHand: 5,
    // aiType: 'Random',
  },
  {
    tavern: "Griffin's Rest",
    location: 'Erathia',
    start: {
      tower: 20,
      wall: 5,
      brickProd: 2,
      gemProd: 2,
      recruitProd: 2,
      bricks: 5,
      gems: 5,
      recruits: 5,
    },
    win: {
      tower: 50,
      resource: 150,
    },
    cardsInHand: 5,
    // aiType: 'Defense',
  },
  {
    tavern: 'Emerald Inn',
    location: 'Tularean Forest',
    start: {
      tower: 20,
      wall: 5,
      brickProd: 2,
      gemProd: 2,
      recruitProd: 2,
      bricks: 5,
      gems: 5,
      recruits: 5,
    },
    win: {
      tower: 50,
      resource: 150,
    },
    cardsInHand: 5,
    // aiType: 'Attack',
  },
  {
    tavern: 'Snobbish Goblin',
    location: 'Deyja',
    start: {
      tower: 25,
      wall: 10,
      brickProd: 3,
      gemProd: 3,
      recruitProd: 3,
      bricks: 5,
      gems: 5,
      recruits: 5,
    },
    win: {
      tower: 75,
      resource: 200,
    },
    cardsInHand: 5,
    // aiType: 'Attack',
  },
  {
    tavern: 'Familiar Place',
    location: 'Bracada Desert',
    start: {
      tower: 20,
      wall: 10,
      brickProd: 3,
      gemProd: 3,
      recruitProd: 3,
      bricks: 5,
      gems: 5,
      recruits: 5,
    },
    win: {
      tower: 75,
      resource: 200,
    },
    cardsInHand: 5,
    // aiType: 'Defense',
  },
  {
    tavern: 'The Blessed Brew',
    location: 'Celeste',
    start: {
      tower: 30,
      wall: 15,
      brickProd: 4,
      gemProd: 4,
      recruitProd: 4,
      bricks: 10,
      gems: 10,
      recruits: 10,
    },
    win: {
      tower: 100,
      resource: 300,
    },
    cardsInHand: 5,
    // aiType: 'Defense',
  },
  {
    tavern: 'The Vampyre Lounge',
    location: 'The Pit',
    start: {
      tower: 30,
      wall: 15,
      brickProd: 4,
      gemProd: 4,
      recruitProd: 4,
      bricks: 10,
      gems: 10,
      recruits: 10,
    },
    win: {
      tower: 100,
      resource: 300,
    },
    cardsInHand: 5,
    // aiType: 'Attack',
  },
  {
    tavern: 'The Laughing Monk',
    location: 'Evermorn Island',
    start: {
      tower: 20,
      wall: 10,
      brickProd: 5,
      gemProd: 5,
      recruitProd: 5,
      bricks: 25,
      gems: 25,
      recruits: 25,
    },
    win: {
      tower: 150,
      resource: 400,
    },
    cardsInHand: 5,
    // aiType: 'Random',
  },
  {
    tavern: "Fortune's Folly",
    location: 'Nighon',
    start: {
      tower: 20,
      wall: 10,
      brickProd: 1,
      gemProd: 1,
      recruitProd: 1,
      bricks: 15,
      gems: 15,
      recruits: 15,
    },
    win: {
      tower: 200,
      resource: 500,
    },
    cardsInHand: 5,
    // aiType: 'Attack',
  },
  {
    tavern: "Miner's Only",
    location: 'Barrow Downs',
    start: {
      tower: 20,
      wall: 50,
      brickProd: 1,
      gemProd: 1,
      recruitProd: 5,
      bricks: 5,
      gems: 5,
      recruits: 25,
    },
    win: {
      tower: 100,
      resource: 300,
    },
    cardsInHand: 5,
    // aiType: 'Random',
  },
  {
    tavern: 'The Loyal Mercenary',
    location: 'Tidewater',
    start: {
      tower: 10,
      wall: 20,
      brickProd: 3,
      gemProd: 1,
      recruitProd: 2,
      bricks: 15,
      gems: 5,
      recruits: 10,
    },
    win: {
      tower: 125,
      resource: 350,
    },
    cardsInHand: 5,
    // aiType: 'Attack',
  },
  {
    tavern: 'The Potted Pixie',
    location: 'Avlee',
    start: {
      tower: 10,
      wall: 20,
      brickProd: 3,
      gemProd: 1,
      recruitProd: 2,
      bricks: 15,
      gems: 5,
      recruits: 10,
    },
    win: {
      tower: 125,
      resource: 350,
    },
    cardsInHand: 5,
    // aiType: 'Defense',
  },
  {
    tavern: "Grogg's Grog",
    location: 'Stone City',
    start: {
      tower: 50,
      wall: 50,
      brickProd: 5,
      gemProd: 3,
      recruitProd: 5,
      bricks: 20,
      gems: 10,
      recruits: 20,
    },
    win: {
      tower: 100,
      resource: 300,
    },
    cardsInHand: 5,
    // aiType: 'Random',
  },
]
