import { SettingsType } from '../types/state'

export const preSettings: SettingsType[] = [
  {
    settingsName: 'On The House - Harmondale',
    start: {
      tower: 15,
      wall: 5,
      brickProd: 2,
      gemProd: 2,
      recruitProd: 2,
      bricks: 10,
      gems: 10,
      recruits: 10,
    },
    win: {
      tower: 30,
      resource: 100,
    },
    cardsInHand: 5,
    // aiType: 'Random',
  },
  {
    settingsName: "Griffin's Rest - Erathia",
    start: {
      tower: 20,
      wall: 5,
      brickProd: 2,
      gemProd: 2,
      recruitProd: 2,
      bricks: 5,
      gems: 5,
      recruits: 5,
    },
    win: {
      tower: 50,
      resource: 150,
    },
    cardsInHand: 5,
    // aiType: 'Defense',
  },
  {
    settingsName: 'Emerald Inn - Tularean Forest',
    start: {
      tower: 20,
      wall: 5,
      brickProd: 2,
      gemProd: 2,
      recruitProd: 2,
      bricks: 5,
      gems: 5,
      recruits: 5,
    },
    win: {
      tower: 50,
      resource: 150,
    },
    cardsInHand: 5,
    // aiType: 'Attack',
  },
  {
    settingsName: 'Snobbish Goblin - Deyja',
    start: {
      tower: 25,
      wall: 10,
      brickProd: 3,
      gemProd: 3,
      recruitProd: 3,
      bricks: 5,
      gems: 5,
      recruits: 5,
    },
    win: {
      tower: 75,
      resource: 200,
    },
    cardsInHand: 5,
    // aiType: 'Attack',
  },
  {
    settingsName: 'Familiar Place - Bracada Desert',
    start: {
      tower: 20,
      wall: 10,
      brickProd: 3,
      gemProd: 3,
      recruitProd: 3,
      bricks: 5,
      gems: 5,
      recruits: 5,
    },
    win: {
      tower: 75,
      resource: 200,
    },
    cardsInHand: 5,
    // aiType: 'Defense',
  },
  {
    settingsName: 'The Blessed Brew - Celeste',
    start: {
      tower: 30,
      wall: 15,
      brickProd: 4,
      gemProd: 4,
      recruitProd: 4,
      bricks: 10,
      gems: 10,
      recruits: 10,
    },
    win: {
      tower: 100,
      resource: 300,
    },
    cardsInHand: 5,
    // aiType: 'Defense',
  },
  {
    settingsName: 'The Vampyre Lounge - The Pit',
    start: {
      tower: 30,
      wall: 15,
      brickProd: 4,
      gemProd: 4,
      recruitProd: 4,
      bricks: 10,
      gems: 10,
      recruits: 10,
    },
    win: {
      tower: 100,
      resource: 300,
    },
    cardsInHand: 5,
    // aiType: 'Attack',
  },
  {
    settingsName: 'The Laughing Monk - Evermorn Island',
    start: {
      tower: 20,
      wall: 10,
      brickProd: 5,
      gemProd: 5,
      recruitProd: 5,
      bricks: 25,
      gems: 25,
      recruits: 25,
    },
    win: {
      tower: 150,
      resource: 400,
    },
    cardsInHand: 5,
    // aiType: 'Random',
  },
  {
    settingsName: "Fortune's Folly - Nighon",
    start: {
      tower: 20,
      wall: 10,
      brickProd: 1,
      gemProd: 1,
      recruitProd: 1,
      bricks: 15,
      gems: 15,
      recruits: 15,
    },
    win: {
      tower: 200,
      resource: 500,
    },
    cardsInHand: 5,
    // aiType: 'Attack',
  },
  {
    settingsName: "Miner's Only - Barrow Downs",
    start: {
      tower: 20,
      wall: 50,
      brickProd: 1,
      gemProd: 1,
      recruitProd: 5,
      bricks: 5,
      gems: 5,
      recruits: 25,
    },
    win: {
      tower: 100,
      resource: 300,
    },
    cardsInHand: 5,
    // aiType: 'Random',
  },
  {
    settingsName: 'The Loyal Mercenary - Tidewater',
    start: {
      tower: 10,
      wall: 20,
      brickProd: 3,
      gemProd: 1,
      recruitProd: 2,
      bricks: 15,
      gems: 5,
      recruits: 10,
    },
    win: {
      tower: 125,
      resource: 350,
    },
    cardsInHand: 5,
    // aiType: 'Attack',
  },
  {
    settingsName: 'The Potted Pixie - Avlee',
    start: {
      tower: 10,
      wall: 20,
      brickProd: 3,
      gemProd: 1,
      recruitProd: 2,
      bricks: 15,
      gems: 5,
      recruits: 10,
    },
    win: {
      tower: 125,
      resource: 350,
    },
    cardsInHand: 5,
    // aiType: 'Defense',
  },
  {
    settingsName: "Grogg's Grog - Stone City",
    start: {
      tower: 50,
      wall: 50,
      brickProd: 5,
      gemProd: 3,
      recruitProd: 5,
      bricks: 20,
      gems: 10,
      recruits: 20,
    },
    win: {
      tower: 100,
      resource: 300,
    },
    cardsInHand: 5,
    // aiType: 'Random',
  },
]
