import { SettingsType } from '../types/state'

export const preSettings: SettingsType[] = [
  {
    // name: 'On The House',
    // location: 'Harmondale',
    tower: 15,
    wall: 5,
    brickProd: 2,
    gemProd: 2,
    recruitProd: 2,
    bricks: 10,
    gems: 10,
    recruits: 10,
    winTower: 30,
    winResource: 100,
    cardsInHand: 5,
    // aiType: 'Random',
  },
  {
    // name: "Griffin's Rest",
    // location: 'Erathia',
    tower: 20,
    wall: 5,
    brickProd: 2,
    gemProd: 2,
    recruitProd: 2,
    bricks: 5,
    gems: 5,
    recruits: 5,
    winTower: 50,
    winResource: 150,
    cardsInHand: 5,
    // aiType: 'Defense',
  },
  // {
  //   // name: 'Emerald Inn',
  //   // location: 'Tularean Forest',
  //   tower: 20,
  //   wall: 5,
  //   brickProd: 2,
  //   gemProd: 2,
  //   recruitProd: 2,
  //   bricks: 5,
  //   gems: 5,
  //   recruits: 5,
  //   winTower: 50,
  //   winResource: 150,
  //   cardsInHand: 5,
  //   // aiType: 'Attack',
  // },
  {
    // name: 'Snobbish Goblin',
    // location: 'Deyja',
    tower: 25,
    wall: 10,
    brickProd: 3,
    gemProd: 3,
    recruitProd: 3,
    bricks: 5,
    gems: 5,
    recruits: 5,
    winTower: 75,
    winResource: 200,
    cardsInHand: 5,
    // aiType: 'Attack',
  },
  {
    // name: 'Familiar Place',
    // location: 'Bracada Desert',
    tower: 20,
    wall: 10,
    brickProd: 3,
    gemProd: 3,
    recruitProd: 3,
    bricks: 5,
    gems: 5,
    recruits: 5,
    winTower: 75,
    winResource: 200,
    cardsInHand: 5,
    // aiType: 'Defense',
  },
  {
    // name: 'The Blessed Brew',
    // location: 'Celeste',
    tower: 30,
    wall: 15,
    brickProd: 4,
    gemProd: 4,
    recruitProd: 4,
    bricks: 10,
    gems: 10,
    recruits: 10,
    winTower: 100,
    winResource: 300,
    cardsInHand: 5,
    // aiType: 'Defense',
  },
  // {
  //   // name: 'The Vampyre Lounge',
  //   // location: 'The Pit',
  //   tower: 30,
  //   wall: 15,
  //   brickProd: 4,
  //   gemProd: 4,
  //   recruitProd: 4,
  //   bricks: 10,
  //   gems: 10,
  //   recruits: 10,
  //   winTower: 100,
  //   winResource: 300,
  //   cardsInHand: 5,
  //   // aiType: 'Attack',
  // },
  {
    // name: 'The Laughing Monk',
    // location: 'Evermorn Island',
    tower: 20,
    wall: 10,
    brickProd: 5,
    gemProd: 5,
    recruitProd: 5,
    bricks: 25,
    gems: 25,
    recruits: 25,
    winTower: 150,
    winResource: 400,
    cardsInHand: 5,
    // aiType: 'Random',
  },
  {
    // name: "Fortune's Folly",
    // location: 'Nighon',
    tower: 20,
    wall: 10,
    brickProd: 1,
    gemProd: 1,
    recruitProd: 1,
    bricks: 15,
    gems: 15,
    recruits: 15,
    winTower: 200,
    winResource: 500,
    cardsInHand: 5,
    // aiType: 'Attack',
  },
  {
    // name: "Miner's Only",
    // location: 'Barrow Downs',
    tower: 20,
    wall: 50,
    brickProd: 1,
    gemProd: 1,
    recruitProd: 5,
    bricks: 5,
    gems: 5,
    recruits: 25,
    winTower: 100,
    winResource: 300,
    cardsInHand: 5,
    // aiType: 'Random',
  },
  {
    // name: 'The Loyal Mercenary',
    // location: 'Tidewater',
    tower: 10,
    wall: 20,
    brickProd: 3,
    gemProd: 1,
    recruitProd: 2,
    bricks: 15,
    gems: 5,
    recruits: 10,
    winTower: 125,
    winResource: 350,
    cardsInHand: 5,
    // aiType: 'Attack',
  },
  // {
  //   // name: 'The Potted Pixie',
  //   // location: 'Avlee',
  //   tower: 10,
  //   wall: 20,
  //   brickProd: 3,
  //   gemProd: 1,
  //   recruitProd: 2,
  //   bricks: 15,
  //   gems: 5,
  //   recruits: 10,
  //   winTower: 125,
  //   winResource: 350,
  //   cardsInHand: 5,
  //   // aiType: 'Defense',
  // },
  {
    // name: "Grogg's Grog",
    // location: 'Stone City',
    tower: 50,
    wall: 50,
    brickProd: 5,
    gemProd: 3,
    recruitProd: 5,
    bricks: 20,
    gems: 10,
    recruits: 20,
    winTower: 100,
    winResource: 300,
    cardsInHand: 5,
    // aiType: 'Random',
  },
  // {
  //   // name: 'The Grog and Grub',
  //   // location: 'Dagger Wound Island',
  //   tower: 15,
  //   wall: 5,
  //   brickProd: 2,
  //   gemProd: 2,
  //   recruitProd: 2,
  //   bricks: 10,
  //   gems: 10,
  //   recruits: 10,
  //   winTower: 30,
  //   winResource: 100,
  //   cardsInHand: 5,
  //   // aiType: '',
  // },
  // {
  //   // name: "Kessel's Kantina",
  //   // location: 'Ravenshore',
  //   tower: 20,
  //   wall: 5,
  //   brickProd: 2,
  //   gemProd: 2,
  //   recruitProd: 2,
  //   bricks: 5,
  //   gems: 5,
  //   recruits: 5,
  //   winTower: 50,
  //   winResource: 150,
  //   cardsInHand: 5,
  //   // aiType: '',
  // },
  // {
  //   // name: 'Profit House',
  //   // location: 'Alvar',
  //   tower: 20,
  //   wall: 5,
  //   brickProd: 2,
  //   gemProd: 2,
  //   recruitProd: 2,
  //   bricks: 5,
  //   gems: 5,
  //   recruits: 5,
  //   winTower: 50,
  //   winResource: 150,
  //   cardsInHand: 5,
  //   // aiType: '',
  // },
  // {
  //   // name: 'Parched Throat',
  //   // location: 'Ironsand Desert',
  //   tower: 25,
  //   wall: 10,
  //   brickProd: 3,
  //   gemProd: 3,
  //   recruitProd: 3,
  //   bricks: 5,
  //   gems: 5,
  //   recruits: 5,
  //   winTower: 75,
  //   winResource: 200,
  //   cardsInHand: 5,
  //   // aiType: '',
  // },
  // {
  //   // name: "Dragon's Blood Inn",
  //   // location: 'Garrote Gorge',
  //   tower: 20,
  //   wall: 10,
  //   brickProd: 3,
  //   gemProd: 3,
  //   recruitProd: 3,
  //   bricks: 5,
  //   gems: 5,
  //   recruits: 5,
  //   winTower: 75,
  //   winResource: 200,
  //   cardsInHand: 5,
  //   // aiType: '',
  // },
  // {
  //   // name: 'Black Company',
  //   // location: 'Shadowspire',
  //   tower: 30,
  //   wall: 15,
  //   brickProd: 4,
  //   gemProd: 4,
  //   recruitProd: 4,
  //   bricks: 10,
  //   gems: 10,
  //   recruits: 10,
  //   winTower: 100,
  //   winResource: 300,
  //   cardsInHand: 5,
  //   // aiType: '',
  // },
  // {
  //   // name: "Traveler's Rest",
  //   // location: 'Murmurwoods',
  //   tower: 30,
  //   wall: 15,
  //   brickProd: 4,
  //   gemProd: 4,
  //   recruitProd: 4,
  //   bricks: 10,
  //   gems: 10,
  //   recruits: 10,
  //   winTower: 100,
  //   winResource: 300,
  //   cardsInHand: 5,
  //   // aiType: '',
  // },
  // {
  //   // name: "Bull's Eye Inn",
  //   // location: 'Ravage Roaming',
  //   tower: 20,
  //   wall: 10,
  //   brickProd: 5,
  //   gemProd: 5,
  //   recruitProd: 5,
  //   bricks: 25,
  //   gems: 25,
  //   recruits: 25,
  //   winTower: 150,
  //   winResource: 400,
  //   cardsInHand: 5,
  //   // aiType: '',
  // },
  // {
  //   // name: "Pirate's Rest",
  //   // location: 'Regna',
  //   tower: 20,
  //   wall: 10,
  //   brickProd: 1,
  //   gemProd: 1,
  //   recruitProd: 1,
  //   bricks: 15,
  //   gems: 15,
  //   recruits: 15,
  //   winTower: 200,
  //   winResource: 500,
  //   cardsInHand: 5,
  //   // aiType: '',
  // },
  // {
  //   // name: 'The Dancing Ogre',
  //   // location: 'Ravenshore',
  //   tower: 20,
  //   wall: 50,
  //   brickProd: 1,
  //   gemProd: 1,
  //   recruitProd: 5,
  //   bricks: 5,
  //   gems: 5,
  //   recruits: 25,
  //   winTower: 100,
  //   winResource: 300,
  //   cardsInHand: 5,
  //   // aiType: '',
  // },
  // {
  //   // name: "Miho's Roadhouse",
  //   // location: 'Alvar',
  //   tower: 10,
  //   wall: 20,
  //   brickProd: 3,
  //   gemProd: 1,
  //   recruitProd: 2,
  //   bricks: 15,
  //   gems: 5,
  //   recruits: 10,
  //   winTower: 125,
  //   winResource: 350,
  //   cardsInHand: 5,
  //   // aiType: '',
  // },
]
