name: Deploy

on:
  push:
    tags:
      - 'v*'

jobs:
  gh-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
      - name: Build App
        run: |
          bun install:nooptional
          bun run build
      - name: Deploy to GitHub Pages (in another repo)
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-directory: 'dist'
          destination-github-username: 'arcomage'
          destination-repository-name: 'arcomage.github.io'
          user-email: tomchen.org@gmail.com
          target-branch: gh-pages
